# Generated by Django 4.2 on 2024-07-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.authormodel', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_books', to=settings.AUTH_USER_MODEL, verbose_name='Favorites'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.genremodel', verbose_name='Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewmodel',
            unique_together={('user', 'book')},
        ),
    ]
